CREATE TABLE `countries` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `englishLongName` varchar(64) NOT NULL CHECK (length(`englishShortName`) <= length(`englishLongName`)) COMMENT 'The official / long / full name of a country, omitting any leading articles, such as "The". In the case of the United States, this field would be "United States of America".',
  `englishShortName` varchar(64) NOT NULL CHECK (length(`englishShortName`) <= length(`englishLongName`)) COMMENT 'A shorter name of a country, omitting any leading articles, such as "The". In the case of the United States, this would be "United States"',
  `englishSingularNationalNoun` varchar(32) DEFAULT NULL COMMENT 'The English noun used to describe a singular citizen of this country. In the case of the United States, this would be "American".',
  `englishPluralNationalNoun` varchar(32) DEFAULT NULL COMMENT 'The English noun used to describe plural citizens of this country. In the case of the United States, this would be "Americans".',
  `englishNationalAdjective` varchar(32) DEFAULT NULL COMMENT 'The English adjective used to describe something that is associated with this country. In the case of the United States, this would be "American".',
  `nativeLongName` varchar(64) DEFAULT NULL CHECK (ifnull(length(`nativeShortName`),0) <= length(`nativeLongName`)) COMMENT 'The official / long / full name of a country in its native language. In the case of Germany, this would be "Deutschland".',
  `nativeShortName` varchar(32) DEFAULT NULL CHECK (length(`nativeShortName`) < ifnull(length(`nativeLongName`),100)) COMMENT 'A shorter name of a country in its native language.',
  `nativeSingularNationalNoun` varchar(32) DEFAULT NULL COMMENT 'The noun in this country''s native language used to describe a singular citizen of this country. In the case of the United States, this would be "American".',
  `nativePluralNationalNoun` varchar(32) DEFAULT NULL COMMENT 'The noun in this country''s native language used to describe plural citizens of this country. In the case of the United States, this would be "Americans".',
  `nativeNationalAdjective` varchar(32) DEFAULT NULL COMMENT 'The adjective in this country''s native language used to describe something that is associated with this country. In the case of the United States, this would be "American".',
  `etymology` text DEFAULT NULL COMMENT 'A description of the origin of the name of the country.',
  `background` text DEFAULT NULL COMMENT 'A brief history and description of the country.',
  `iso3166Alpha2Code` char(2) DEFAULT NULL CHECK (`iso3166Alpha2Code` regexp '[A-Z]{2}') COMMENT 'The two-character alphabetic code specified in ISO 3166 to identify this country.',
  `iso3166Alpha3Code` char(3) DEFAULT NULL CHECK (`iso3166Alpha3Code` regexp '[A-Z]{3}') COMMENT 'The three-character alphabetic code specified in ISO 3166 to identify this country.',
  `iso3166NumericCode` smallint(5) unsigned DEFAULT NULL COMMENT 'The numeric code specified in ISO 3166 to identify this country.',
  `oidArcUnderISOMemberBody` smallint(5) unsigned DEFAULT NULL COMMENT 'The official object identifier under 1.2 used to describe this country.',
  `oidArcUnderJointISOITUCountry` smallint(5) unsigned DEFAULT NULL COMMENT 'The official object identifier under 2.16 used to describe this country.',
  `fipsCountryCode` char(2) DEFAULT NULL CHECK (`fipsCountryCode` regexp '[A-Z]{2}') COMMENT 'The two-character alphabetic code specified in FIPS 10-4 used to identify this country.',
  `unitedNationsM49Code` char(3) DEFAULT NULL CHECK (`unitedNationsM49Code` regexp '[0-9]{3}') COMMENT 'The three-character numeric code used by the United Nations to identify a country, per specification M.49.',
  `internationalOlympicCommitteeCode` char(3) DEFAULT NULL CHECK (`internationalOlympicCommitteeCode` regexp '[A-Z]{3}') COMMENT 'The three-character alphabetic code used to identify a National Olympic Committee (NOC) associated with this country.',
  `fifaCountryCode` char(3) DEFAULT NULL CHECK (`fifaCountryCode` regexp '[A-Z]{3}') COMMENT 'The three-character alphabetic code used to identify a country that is a member of the Fédération Internationale de Football Association.',
  `topLevelDomain` char(2) DEFAULT NULL CHECK (`topLevelDomain` regexp '[A-Z]{2}') COMMENT 'The Country-Code Top Level Domain (ccTLD) associated with this country.',
  `distinguishedName` char(4) GENERATED ALWAYS AS (concat('C=',`iso3166Alpha2Code`)) VIRTUAL,
  `relativeDistinguishedName` char(4) GENERATED ALWAYS AS (concat('C=',`iso3166Alpha2Code`)) VIRTUAL,
  `locationDescription` text DEFAULT NULL,
  `terrainDescription` text DEFAULT NULL,
  `naturalResourcesDescription` text DEFAULT NULL,
  `borderGeoJSON` mediumtext DEFAULT NULL CHECK (json_valid(`borderGeoJSON`)),
  `borderGML` mediumtext DEFAULT NULL,
  `borderKML` mediumtext DEFAULT NULL,
  `landAreaInSquaredKilometers` int(10) unsigned DEFAULT NULL,
  `waterAreaInSquaredKilometers` int(10) unsigned DEFAULT NULL,
  `totalAreaInSquaredKilometers` int(10) unsigned GENERATED ALWAYS AS (`landAreaInSquaredKilometers` + `waterAreaInSquaredKilometers`) VIRTUAL,
  `latitude` float DEFAULT NULL CHECK (`latitude` >= -90.0 and `latitude` <= 90.0) COMMENT 'The geographic displacement from the Equator, measured in degrees',
  `longitude` float DEFAULT NULL CHECK (`longitude` > -180.0 and `longitude` <= 180.0) COMMENT 'The geographic displacement from the Prime Meridian, measured in degrees',
  `continent` bigint(20) unsigned DEFAULT NULL,
  `parentUnitedNationsM49SubregionCode` char(3) DEFAULT NULL,
  `internationalAtomicEnergyAgencyAreaID` bigint(20) unsigned DEFAULT NULL,
  `highestPointInMeters` smallint(6) DEFAULT NULL CHECK (`highestPointInMeters` > ifnull(`lowestPointInMeters`,-20000)),
  `highestPointName` varchar(64) DEFAULT NULL,
  `lowestPointInMeters` smallint(6) DEFAULT NULL CHECK (ifnull(`highestPointInMeters`,20000) > `lowestPointInMeters`),
  `lowestPointName` varchar(64) DEFAULT NULL,
  `averageElevationInMeters` smallint(6) DEFAULT NULL CHECK (ifnull(`highestPointInMeters`,20000) > `averageElevationInMeters` and `averageElevationInMeters` > ifnull(`lowestPointInMeters`,-20000)),
  `borderLengthInKilometers` smallint(5) unsigned DEFAULT NULL,
  `coastlineLengthInKilometers` smallint(5) unsigned DEFAULT NULL,
  `atLeastPartiallyWithinHajnalLines` tinyint(1) DEFAULT 0,
  `climateDescription` text DEFAULT NULL,
  `legalSystemDescription` text DEFAULT NULL,
  `world` bigint(20) unsigned DEFAULT NULL,
  `independent` tinyint(1) DEFAULT NULL,
  `landlocked` tinyint(1) DEFAULT NULL,
  `dateSovereigntyDeclared` date DEFAULT NULL,
  `dateSovereigntyRecognized` date DEFAULT NULL,
  `terminationDate` date DEFAULT NULL,
  `extant` tinyint(1) DEFAULT NULL,
  `extinct` tinyint(1) DEFAULT NULL,
  `capitalName` varchar(64) DEFAULT NULL,
  `hasUniversalSuffrage` tinyint(1) DEFAULT NULL,
  `hasCompulsorySuffrage` tinyint(1) DEFAULT NULL,
  `ageOfSuffrage` tinyint(3) unsigned DEFAULT NULL,
  `hasFemaleSuffrage` tinyint(1) DEFAULT NULL,
  `dualCitizenshipRecognized` tinyint(1) DEFAULT NULL,
  `citizenShipByDescentOnly` tinyint(1) DEFAULT NULL,
  `citizenShipByBirth` tinyint(1) DEFAULT NULL,
  `residencyYearsForNaturalization` tinyint(3) unsigned DEFAULT NULL,
  `minimumAgeForMilitaryService` tinyint(3) unsigned DEFAULT NULL,
  `conscriptionUsed` tinyint(1) DEFAULT NULL,
  `permitsAlcoholConsumption` tinyint(1) DEFAULT NULL,
  `permitsTobaccoConsumption` tinyint(1) DEFAULT NULL,
  `permitsMarijuanaConsumption` tinyint(1) DEFAULT NULL,
  `permitsCivilianFirearmOwnership` tinyint(1) DEFAULT NULL,
  `minimumAgeToConsumeAlcohol` tinyint(3) unsigned DEFAULT NULL CHECK (`permitsAlcoholConsumption`),
  `minimumAgeToConsumeTobacco` tinyint(3) unsigned DEFAULT NULL CHECK (`permitsTobaccoConsumption`),
  `minimumAgeToConsumeMarijuana` tinyint(3) unsigned DEFAULT NULL CHECK (`permitsMarijuanaConsumption`),
  `minimumAgeToOwnAFirearm` tinyint(3) unsigned DEFAULT NULL CHECK (`permitsCivilianFirearmOwnership`),
  `minimumAgeOfSexualConsent` tinyint(3) unsigned DEFAULT NULL,
  `homosexualMarriageRecognized` tinyint(1) DEFAULT NULL CHECK (`homosexualityLegalized`),
  `homosexualityLegalized` tinyint(1) DEFAULT NULL,
  `hasOfficialReligion` tinyint(1) DEFAULT NULL,
  `economyDescription` text DEFAULT NULL,
  `unionsPermitted` tinyint(1) DEFAULT NULL,
  `hasACentralBank` tinyint(1) DEFAULT NULL,
  `sovereignCurrency` tinyint(1) DEFAULT NULL,
  `flagDescription` text DEFAULT NULL,
  `flagUnicode` char(4) DEFAULT NULL,
  `flagIcon16x16` blob DEFAULT NULL,
  `flagIcon32x32` blob DEFAULT NULL,
  `flagIcon48x48` blob DEFAULT NULL,
  `flagIcon64x64` mediumblob DEFAULT NULL,
  `flagIcon128x128` mediumblob DEFAULT NULL,
  `flagIcon256x256` mediumblob DEFAULT NULL,
  `nationalSymbols` text DEFAULT NULL,
  `anthemName` tinytext DEFAULT NULL,
  `residencyRequirementForNaturalizationInYears` tinyint(3) unsigned DEFAULT NULL,
  `privateOwnershipOfFirearmsPermitted` tinyint(1) DEFAULT NULL COMMENT 'Whether the government permits private ownership of firearms.',
  `privateOwnershipOfFirearmsShallIssue` tinyint(1) DEFAULT NULL COMMENT 'Whether, subject to fulfillment of legal conditions, the authorities may not deny license and/or firearm(s).',
  `personalProtectionFirearmsPermitted` tinyint(1) DEFAULT NULL COMMENT 'Whether the government permits private ownership of firearms for personal protection.',
  `personalProtectionFirearmsShallIssue` tinyint(1) DEFAULT NULL COMMENT 'Whether, subject to fulfillment of legal conditions, the authorities may not deny license and/or firearm(s) for personal protection.',
  `personalProtectionFirearmsRequireSpecificReason` tinyint(1) DEFAULT NULL COMMENT 'Whether a specific reason is required for possession of a firearm for self-defense.',
  `openCarryFirearmsPermitted` tinyint(1) DEFAULT NULL COMMENT 'Whether the government permits open carry of firearms, even if it requires licensing, background checks, fees, or other restrictions.',
  `openCarryFirearmsShallIssue` tinyint(1) DEFAULT NULL COMMENT 'Whether, subject to fulfillment of legal conditions, the authorities may not deny licenses to openly carry firearms.',
  `openCarryFirearmsRequiresSpecificReason` tinyint(1) DEFAULT NULL COMMENT 'Whether a specific reason is required for open carry of firearms.',
  `concealedCarryFirearmsPermitted` tinyint(1) DEFAULT NULL COMMENT 'Whether the government permits concealed carry of firearms, even if it requires licensing, background checks, fees, or other restrictions.',
  `concealedCarryFirearmsShallIssue` tinyint(1) DEFAULT NULL COMMENT 'Whether, subject to fulfillment of legal conditions, the authorities may not deny licenses to concealed carry firearms.',
  `concealedCarryFirearmsRequiresSpecificReason` tinyint(1) DEFAULT NULL COMMENT 'Whether a specific reason is required for concealed carry of firearms.',
  `fullyAutomaticFirearmsPermitted` tinyint(1) DEFAULT NULL COMMENT 'Whether the government permits possession of fully-automatic firearms, even if it requires licensing, background checks, fees, or other restrictions.',
  `fullyAutomaticFirearmsShallIssue` tinyint(1) DEFAULT NULL COMMENT 'Whether, subject to fulfillment of legal conditions, the authorities may not deny licenses to possess automatic firearms.',
  `fullyAutomaticFirearmsRequiresSpecificReason` tinyint(1) DEFAULT NULL COMMENT 'Whether a specific reason is required for possession of a fully-automatic firearm.',
  `limitedFirearmMagazineCapacity` tinyint(1) DEFAULT NULL COMMENT 'Whether there are legal limitations on the number of bullets in a firearm magazine.',
  `backgroundChecksForFirearmOwnership` tinyint(1) DEFAULT NULL COMMENT 'Whether background checks or medical checks are legally required for firearm ownership.',
  `firearmRegistrationRequired` tinyint(1) DEFAULT NULL COMMENT 'Whether all firearms are legally required to be registered with the government.',
  `freeRegistrationOfFirearms` tinyint(1) DEFAULT NULL COMMENT 'Whether the registration of firearms does not cost money.',
  `maximumPenaltyInYearsForFirearmViolation` tinyint(3) unsigned DEFAULT NULL COMMENT 'The maximum penalty, in years, for non-violent nor inchoate violations of firearms laws.',
  `carryingFirearmsLegalWithoutPermit` tinyint(1) DEFAULT NULL COMMENT 'Whether firearms may be legally carried without a permit.',
  `freeHealthcare` tinyint(1) DEFAULT NULL COMMENT 'Free health care is free of charge or a nominal fee to all its citizens, with no exclusions based on income or wealth.',
  `universalHealthcare` tinyint(1) DEFAULT NULL COMMENT 'Universal health care is a health care system that provides healthcare and financial protection to more than 90% of the citizens of a particular country.',
  `startYearOfUniversalHealthcare` year(4) DEFAULT NULL COMMENT 'The year in which universal healthcare was instated.',
  `healthcareSystemDescription` tinytext DEFAULT NULL COMMENT 'A short description of the healthcare system',
  `publicFinanceWebHomepage` tinytext DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q1.1: PF home page (web link to main PF home page)',
  `officialNameOfFinanceMinistryDepartment` tinytext DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q1.2: Official Name of Finance Ministry / Department',
  `hasDedicatedPublicFinancePublicationWebsite` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q1.3: Is there a dedicated PF publication web site?',
  `ministryOfFinancePublicationWebsite` tinytext DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q1.4: If Yes to Q1.3 (1 or 2) > PF publication web link',
  `hasWebsiteOrDocumentationOnFMISSolution` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q2.1: Is there a web site / doc on FMIS solution?',
  `uriOfWebsiteOrDocumentationOnFMISSolution` tinytext DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q2.2: If Yes to Q2.1 (1 or 2) > Related web link',
  `publicFinanceDataSourceIsDynamic` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q3.1: What is the source of Public Finance data?',
  `publicFinanceDynamicDataSourceURI` tinytext DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q3.2: If Dynamic (2 or 3) > Related web link',
  `publicFinanceDataIsOnlineEditableAndFree` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q3.3: Presence of Open Data (online, editable, free)',
  `publicFinanceOpenDataURI` tinytext DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q3.4: If Yes to Open Data (1) > Related web link',
  `publicFinanceSystemNameVisibleInReports` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q3.5: Is System Name visible in reports?',
  `publicFinanceSystemTimeStampVisibleInReports` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q3.6: Is System Time Stamp visible in reports?',
  `publishesApprovedAnnualBudget` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q6.1: Approved annual budget published?',
  `annualBudgetPublishedRegularly` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q6.2: If Yes to Q6.1 (1) > Regularity of publication',
  `startingYearOfPublishingAnnualBudgetData` year(4) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q6.3: Since > Starting year of published annual budget data (regular/irregular)',
  `publishesInvestmentPlan` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q8.1: Public investment plans?',
  `investmentPlanPublishedRegularly` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q8.2: If Yes to Q8.1 (1) > Regularity of publication',
  `startingYearOfPublishingInvestmentPlan` year(4) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q8.3: Since > Starting year of published investment plans (regular/irregular)',
  `publishesBudgetExecutionResults` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q9.1: Budget execution results?',
  `weeksBetweenPublicationOfBudgetExecutionResults` tinyint(3) unsigned DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q9.2: If Yes to Q9.1 (1) > Frequency of publication  (most frequently published)',
  `budgetExecutionResultsPublishedRegularly` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q9.3: If Yes to Q9.1 (1) > Regularity of publication',
  `startingYearOfPublishingBudgetExecutionResults` year(4) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q9.4: Since > Starting year of published execution results (regular/irregular)',
  `budgetOperationsIsExternallyAudited` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q10.1: External audit of central gov budget operations?',
  `budgetOperationsAuditPublishedRegularly` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q10.2: If Yes to Q10.1 (1) > Regularity of publication',
  `startingYearOfPublishingBudgetOperationsAudit` year(4) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q10.3: Since > Starting year of published budget audits (regular/irregular)',
  `budgetContainsConsolidatedResultsForKeyBudgetUsers` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q11.1: Consolidated results for key budget users?',
  `budgetContainsSectorAnalysis` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q11.2: Sector analysis?',
  `budgetContainsRegionalAnalysis` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q11.3: Regional analysis?',
  `budgetContainsGenderAnalysis` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q11.4: Gender analysis?',
  `budgetContainsChildrenAndYouthSpending` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q11.5: Analysis of spending for Children and Youth?',
  `budgetContainsDebtData` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q11.6: Debt data?',
  `budgetContainsForeignAidAndGrantsData` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q11.7: Foreign aid/grants?',
  `budgetContainsFiscalDataOnSubnationalGovernments` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q11.8: Fiscal data on sub-national gov/municipalities?',
  `budgetContainsFinancialStatements` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q11.9: Financial Statements?',
  `budgetContainsPublicProcurementAndContracts` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q11.10: Public procurement and contracts?',
  `budgetContainsOtherPublicFinanceData` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q11.11: Other PF Data?',
  `otherPublicFinanceDataURI` tinytext DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q11.12: If Yes to Q11.11 (1) > Related web link',
  `hasOpenGovernmentDataURI` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q12.1: Open Government/Open Data web site?',
  `openGovernmentDataURI` tinytext DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q12.2: If Yes to Q12.1 (1) > Related web link',
  `hasHarmonizedPublicAccountingForAllLevelsOfGovernment` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q14.1: Is there a harmonized public accounting system for central + state/local governments and municipalities?',
  `harmonizedPublicAccountingForAllLevelsOfGovernmentURI` tinytext DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q14.2: If Yes to Q14.1 (1) > Related web link',
  `centralBankURI` tinytext DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q15.4: URL of the Central Bank',
  `centralBankName` tinytext DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q15.5: Official Name of Central Bank',
  `publicFinanceReportsComplyWithUnitedNationsCOFOGStandards` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q18.1: Compliance with specific int''l standards?',
  `publicFinanceReportsComplyWithIMFGFSStandards` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q18.1: Compliance with specific int''l standards?',
  `keepsPublicFinanceWebsiteUsageStatistics` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q19.1: Web Statistics (e.g. visitors, freq visited web pages)?',
  `publicFinanceWebsiteSupportsEmailOrFormsFeedback` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q19.2: Which platforms are available for feedback provision?',
  `publicFinanceWebsiteSupportsPhysicalMailOrFaxOrPhoneFeedback` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Q19.2: Which platforms are available for feedback provision?',
  `financeManagementInformationSystemSolutionAbbrevation` varchar(64) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, FMIS / TS: Abbreviation of the FMIS solution',
  `financeManagementInformationSystemSolutionName` tinytext DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, FMIS: Full name of the FMIS solution',
  `centralizedPublicFinanceManagement` tinyint(1) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Tpl: PFM topology',
  `startingYearOfFMISBecomingOperational` year(4) DEFAULT NULL COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Op Yr: Year in which the TS/FMIS became operational',
  `openBudgetDataScore` float unsigned DEFAULT NULL CHECK (`openBudgetDataScore` <= 100.00) COMMENT 'From the World Bank FMIS and Open Budget Data Global Dataset, Score: Normalized FMIS & OBD score',
  `worldPressFreedomIndexScore` float unsigned DEFAULT NULL COMMENT 'The World Press Freedom Index Score, as calculated by Reporters Without Borders. See: https://rsf.org/en/world-press-freedom-index.',
  `abortionPermittedToSaveMothersLife` tinyint(1) DEFAULT NULL COMMENT 'Whether abortion is legally permitted if it is done to save the mother''s life.',
  `abortionPermittedToPreserveMothersPhysicalHealth` tinyint(1) DEFAULT NULL COMMENT 'Whether abortion is legally permitted if it is done to preserve the mother''s physical health.',
  `abortionPermittedToPreserveMothersMentalHealth` tinyint(1) DEFAULT NULL COMMENT 'Whether abortion is legally permitted if it is done to preserve the mother''s mental health.',
  `abortionPermittedInCasesOfRapeOrIncest` tinyint(1) DEFAULT NULL COMMENT 'Whether abortion is legally permitted if it the fetus was conceived from rape or incest.',
  `abortionPermittedInCasesOfFetalImpairment` tinyint(1) DEFAULT NULL COMMENT 'Whether abortion is legally permitted if it it is believed that the child will be born with congenital impairments.',
  `abortionPermittedForEconomicOrSocialReasons` tinyint(1) DEFAULT NULL COMMENT 'Whether abortion is legally permitted if it is done for economic or social reasons.',
  `abortionPermittedOnRequest` tinyint(1) DEFAULT NULL COMMENT 'Whether abortion is legally permitted for any reason or no reason at all.',
  `cannabisConsumptionPermittedForRecreation` tinyint(1) DEFAULT NULL COMMENT 'Whether Cannabis consumption is legally permitted for recreational purposes.',
  `cannabisConsumptionPermittedForMedicine` tinyint(1) DEFAULT NULL COMMENT 'Whether Cannabis consumption is legally permitted for medicinal purposes.',
  `cannabisConsumptionPermittedForCultivation` tinyint(1) DEFAULT NULL COMMENT 'Whether the cultivation of Cannabis is legally permitted.',
  `usualLegalBloodAlcoholContentThreshold` float(6,3) unsigned DEFAULT NULL CHECK (`usualLegalBloodAlcoholContentThreshold` <= 100.00) COMMENT 'The threshold of intoxication that applies to non-professional\nnon-novice drivers measured in Blood Alcohol Content (BAC) percentage after\nwhich driving becomes punished by law. One-hundred percent means that there\nis no limit, whereas NULL is used to indicate an unknown value.',
  `ageOfConsentThresholdForLegalSexualRelations` tinyint(3) unsigned DEFAULT NULL COMMENT 'The age in years after which a person can be a party to a legal sexual relationship.',
  `recognizesPolygamy` tinyint(1) DEFAULT NULL COMMENT 'Whether the state recognizes polygamous marriages as legal marriages.',
  `legalizedHomosexualSex` tinyint(1) DEFAULT NULL COMMENT 'Whether homosexual sex is not legally punished.\nSource: https://en.wikipedia.org/wiki/LGBT_rights_by_country_or_territory.',
  `legallyRecognizedSameSexUnions` tinyint(1) DEFAULT NULL COMMENT 'Whether same-sex unions are legally recognized.\nSource: https://en.wikipedia.org/wiki/LGBT_rights_by_country_or_territory.',
  `legallyRecognizedSameSexMarriage` tinyint(1) DEFAULT NULL COMMENT 'Whether same-sex marriage is legally recognized as being equivalent to heterosexual marriages.\nSource: https://en.wikipedia.org/wiki/LGBT_rights_by_country_or_territory.',
  `sameSexCouplesPermittedToAdoptChildren` tinyint(1) DEFAULT NULL COMMENT 'Whether the country permits homosexuals to adopt children.\nSource: https://en.wikipedia.org/wiki/LGBT_rights_by_country_or_territory.',
  `lesbiansGaysAndBisexualsAllowedToServeInTheMilitary` tinyint(1) DEFAULT NULL COMMENT 'Whether lesbians, gays, and bisexuals are allowed to serve in the military.\nSource: https://en.wikipedia.org/wiki/LGBT_rights_by_country_or_territory.',
  `discriminationBySexualOrientationOutlawed` tinyint(1) DEFAULT NULL COMMENT 'Whether discrimination on the basis of sexual-orientation is outlawed.\nSource: https://en.wikipedia.org/wiki/LGBT_rights_by_country_or_territory.',
  `hasLawsConcerningGenderIdentity` tinyint(1) DEFAULT NULL COMMENT 'Whether the country has laws concerning gender identity.\nSource: https://en.wikipedia.org/wiki/LGBT_rights_by_country_or_territory.',
  PRIMARY KEY (`id`),
  UNIQUE KEY `iso3166Alpha2Code` (`iso3166Alpha2Code`),
  UNIQUE KEY `iso3166Alpha3Code` (`iso3166Alpha3Code`),
  UNIQUE KEY `iso3166NumericCode` (`iso3166NumericCode`),
  UNIQUE KEY `oidArcUnderISOMemberBody` (`oidArcUnderISOMemberBody`),
  UNIQUE KEY `oidArcUnderJointISOITUCountry` (`oidArcUnderJointISOITUCountry`),
  UNIQUE KEY `fipsCountryCode` (`fipsCountryCode`),
  UNIQUE KEY `unitedNationsM49Code` (`unitedNationsM49Code`),
  UNIQUE KEY `internationalOlympicCommitteeCode` (`internationalOlympicCommitteeCode`),
  UNIQUE KEY `fifaCountryCode` (`fifaCountryCode`),
  UNIQUE KEY `topLevelDomain` (`topLevelDomain`),
  KEY `continent` (`continent`),
  KEY `parentUnitedNationsM49SubregionCode` (`parentUnitedNationsM49SubregionCode`),
  KEY `internationalAtomicEnergyAgencyAreaID` (`internationalAtomicEnergyAgencyAreaID`),
  KEY `world` (`world`),
  CONSTRAINT `countries_ibfk_1` FOREIGN KEY (`continent`) REFERENCES `continents` (`id`),
  CONSTRAINT `countries_ibfk_2` FOREIGN KEY (`parentUnitedNationsM49SubregionCode`) REFERENCES `unitednationsm49subregions` (`code`),
  CONSTRAINT `countries_ibfk_3` FOREIGN KEY (`internationalAtomicEnergyAgencyAreaID`) REFERENCES `internationalatomicenergyagencyareas` (`id`),
  CONSTRAINT `countries_ibfk_4` FOREIGN KEY (`world`) REFERENCES `worldofthree` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=250 DEFAULT CHARSET=utf8;
